#!/usr/bin/env escript
%% Sponsored by CloudPBX Inc. (http://cloudpbx.ca)
%%
-module(escriptize).

-record('opts', {dirs = ["ebin"], out}).

-export([main/0, main/1]).

main() ->
    io:format("not enough arguments"),
    halt(1).

main(Args) ->
    main(Args, #opts{}).

main(["-d", Dir | Args], Opts) ->
    Dirs = [binary_to_list(D) || D <- re:split(Dir, " ")],
    main(Args, Opts#opts{dirs = Dirs});
main(["-o", Out | Args], Opts) ->
    main(Args, Opts#opts{out = Out});
main([_ | Args], Opts) ->
    main(Args, Opts);
main([], Opts) ->
    run(Opts).

run(#opts{dirs = Dirs, out = Out}) ->
    Files = lists:foldl(fun(Dir, Acc) -> Acc ++ filelib:wildcard(Dir ++ "/*") end, [], Dirs),
    {ok, {"mem", Zip}} = zip:create("mem", Files, ['memory']),
    ok = escript:create(Out, [shebang, {emu_args, "-pa ebin -pa lib/ejson-0.1.0/ebin"}, {archive, Zip}]),
    halt(0).
