#!/usr/bin/env bash

set -e
set -o nounset

#logfile
install_log="/var/log/kazoo_install.log"
#lock_file
lockfile="/var/lock/subsys/setup_rabbitmq.lockfile"

#Files to edit
rabbitmq_env_conf="/etc/kazoo/rabbitmq/rabbitmq-env.conf"

. /opt/kazoo_install/setup_common
trap error_exit SIGHUP SIGTERM EXIT
trap int_exit SIGINT SIGQUIT

################################################################################
# set_value NOTE:
# *_cmd and *_dbg are access commands and debug statements for use in set_value
# TOKEN is replaced using with the $value argument in set_value
# using variable expansion substring replacement
################################################################################
#ask NOTE:
# *_question, *_re, *_hint and *_ref are used by ask
# for getting user input, this allows us to pass one name to ask and do all
# defined actions requrired to provide help, get input, and save it to a var
#### set_value variables #######################################################
# *_dbg - print statement when setting parameter
# *_cmd - command to execute
#### ask variables #############################################################
# *_question - the question to ask when getting the value from user
# *_re       - the re to use to validate repsonse
# *_hint     - the hint to provide in case of blank line, ? or invalid parameter
# *_ref      - the ref to the variable used to store the user requested value
################################################################################

#Rabbit IP ADDRESS
ip_address=""
ip_address_dbg="setting $rabbitmq_env_conf -  = TOKEN"
ip_address_cmd="sed -i 's|NODE_IP_ADDRESS=.*|NODE_IP_ADDRESS=TOKEN|' $rabbitmq_env_conf"
ip_address_question="Please enter the IP address that rabbitmq-server shoud use for listening: "
ip_address_re="$ip_address_regex"
ip_address_hint="This is typically 0.0.0.0 to listen on all IP addresses"
ip_address_ref="ip_address"

interactive(){
    ask ip_address
}

dbg " : configuring rabbitmq : "

check_lock

if [[ ${1:-} =~ -a ]];then
    all_in_one=1
fi

if [  ${all_in_one:-} ];then
   #if allinone we default everything!
   ip_address="0.0.0.0"
else
   info "NOTE: You can type '${NC}?${blue}' in response to any question for a hint"
   interactive
fi

dbg "Applying rabbitmq configuration..."


set_value ip_address $ip_address

clean_exit 
