#!/usr/bin/env bash

set -e
set -o nounset

#logfile
#lock_file
lockfile="/var/lock/subsys/setup_kamailio.lockfile"

#Files to edit
kamailio_local_cfg="/etc/kazoo/kamailio/local.cfg"
kamailio_dispatcher="/etc/kazoo/kamailio/dbtext/dispatcher"

. /opt/kazoo_install/setup_common
trap error_exit SIGHUP SIGTERM ERR EXIT
trap int_exit SIGINT SIGQUIT

declare -a dispatch_list

#KAMAILIO IP ADDRESS
ip_address=""
ip_address_dbg="setting $kamailio_local_cfg - !MY_IP_ADDRESS!TOKEN"
ip_address_cmd="sed -i 's/!MY_IP_ADDRESS!.*!/!MY_IP_ADDRESS!TOKEN!/g' $kamailio_local_cfg"
ip_address_question="Please enter the IP address that kamailio should use for sip (ip_address): "
ip_address_re="$ip_address_regex"
ip_address_hint="IP ADDRESS!"
ip_address_ref="ip_address"

#KAMAILIO HOSTNAME
system_hostname=""
system_hostname_dbg="setting $kamailio_local_cfg - !MY_HOSTNAME!TOKEN"
system_hostname_cmd="sed -i 's/!MY_HOSTNAME!.*!/!MY_HOSTNAME!TOKEN!/g' $kamailio_local_cfg"

#rabbitMQ AMQP server
amqp_address=""
amqp_address_dbg="setting $kamailio_local_cfg - !MY_AMQP_URL!TOKEN"
amqp_address_cmd="sed -i 's|!MY_AMQP_URL!.*!|!MY_AMQP_URL!amqp://guest:guest@TOKEN:5672|g' $kamailio_local_cfg"
amqp_address_question="Please enter the IP address that kamailio should use for amqp (rabbitmq server ip address): "
amqp_address_re=".*"
amqp_address_hint="This is the ip address of your rabbitmq-server"
amqp_address_ref="amqp_address"

#KAMAILIO FREESWITCH DISPATCH IP ADDRESS, PORT, SETID
dispatcher_ip_address="" 
dispatcher_ip_address_question="Please enter your dispatch server IP address (ip_address))"
dispatcher_ip_address_re="$ip_address_regex"
dispatcher_ip_address_hint="This should be your freeswitch IP"
dispatcher_ip_address_ref="dispatcher_ip_address"

dispatcher_port=""
dispatcher_port_question="Please enter the the port for the selected dispatch IP"
dispatcher_port_re="[0-9]+"
dispatcher_port_hint="This is normally 11000"
dispatcher_port_ref="dispatcher_port"

dispatcher_setid=""
dispatcher_setid_question="Please enter the value for setid 1=primary, 2=backup, 3=alternate, 10=Presence, 20=Registrar"
dispatcher_setid_re="[0-9]+"
dispatcher_setid_hint=$(cat << EOF 
This is the dispatcher list, which tells kamailio where to route specific traffic,
use ${red}1${NC}, ${red}2${NC} or ${red}3${NC} for freeswitch, use {$red}10-20${NC} if you have a kamailio or NKSip destination 
you want to use for Presence/Registrar
EOF
)
dispatcher_setid_ref="dispatcher_setid"

set_dispatcher(){
    local tempfile="${kamailio_dispatcher}.tmp"
    while read line;do
        if [[ $line =~ [[:digit:]]+[[:space:]]sip.* ]];then
            for dispatch in "${dispatch_list[@]}";do
                dbg "Adding dispatcher line to $kamailio_dispatcher file - ${dispatch}"
                echo "${dispatch}" >> $tempfile
            done
            #dispatcher file ends with these entries
            mv $tempfile $kamailio_dispatcher
            return 
        else
            echo $line >> $tempfile 
        fi
    done < $kamailio_dispatcher
}

ask_dispatcher(){
    local dispatcher_ip_address
    ask dispatcher_ip_address
    local dispatcher_port
    ask dispatcher_port
    local dispatcher_setid
    ask dispatcher_setid
    dispatch_list+=("${dispatcher_setid} sip:${dispatcher_ip_address}:${dispatcher_port} 1")
   
    local answer 
    confirm "Do you want to add another freeswitch to dispatch list? [y|n]"
    if [[ $answer =~ ^[yY] ]];then
        ask_dispatcher
    fi
}

interactive(){
    ask_dispatcher
    ask amqp_address
    ask ip_address
}

info " : Configuring Kamailio : "
check_root
check_lock
get_system_hostname

check_ip || ask_ip_selection

if [[ ${1:-} =~ -a ]];then
    all_in_one=1
fi

if [  ${all_in_one:-} ];then
   #if allinone we default everything!
   ip_address=$system_ip_address
   hostname=$system_hostname
   dispatch_list+=("1 sip:$system_ip_address:11000 1") 
   ports+=("11000")
   setids+=("1")
else
   info "NOTE: You can type '${NC}?${blue}' in response to any question for a hint"
   interactive
fi

dbg "Applying Kamailio configuration..."

if [[ ${system_ip_address:-} ]];then  
    set_value ip_address $system_ip_address
else
    set_value ip_address $ip_address
fi 

set_value system_hostname $system_hostname

set_dispatcher

clean_exit 
