#!/usr/bin/env bash

set -e
set -o nounset

lockfile="/var/lock/subsys/setup_kazoo.lockfile"

. /opt/kazoo_install/setup_common

trap clean_exit SIGHUP SIGTERM ERR EXIT
trap int_exit SIGINT SIGQUIT


kazoo_config="/etc/kazoo/config.ini"

#KAZOO COOKIE
cookie=""
cookie_dbg="setting $kazoo_config - setcookie = TOKEN"
cookie_cmd="sed -i 's|cookie = .*|cookie = TOKEN|' $kazoo_config"
cookie_question="Please enter your erlang cookie (string): "
cookie_re=".*"
cookie_hint="Cookie should be longish, like 32 chars at least"
cookie_ref="ip_address"

#KAZOO IP
ip_address=""
ip_address_dbg="setting $kazoo_config - ip = \"TOKEN\""
ip_address_cmd="sed -i 's|ip = .*|ip = \"TOKEN\"|' $kazoo_config"
ip_address_question="What IP should we use for kazoo to talk to bigcouch (normally: 127.0.0.1)?: "
ip_address_re="$ip_address_regex"
ip_address_hint="This is generally the haProxy ip address which is normally available via localhost" 
ip_address_ref="ip_address"

####KAZOO AMQP CONFIG
amqp_string=""
amqp_string_dbg="setting amqp config in $kazoo_config - TOKEN"
amqp_string_cmd="sed -i 's|\"amqp://.*\"|\"amqp://TOKEN\"|' $kazoo_config"  

#AMQP IP
amqp_ip=""
amqp_ip_question="What is your AMQP server IP address"
amqp_ip_re="$ip_address_regex"
amqp_ip_hint="This is the ip address of your rabbitmq server?"
amqp_ip_ref="amqp_ip"


ask_amqp_config(){
    ask amqp_ip
    amqp_string="guest:guest@${amqp_ip}:5672"
}

interactive(){
    ask_amqp_config 
    ask ip_address
}

info " : Configuring Kazoo : "
check_root
check_lock
get_default_cookie

if [  ${default_cookie:-} ];then
    cookie="$default_cookie"
else
    ask cookie
    set_cookie_file $cookie
fi


set_value cookie $default_cookie

if [[ ${1:-} =~ -a ]];then
    all_in_one=1
fi

if [  ${all_in_one:-} ];then
   #if allinone we default everything we can
   amqp_string="guest:guest@127.0.0.1:5672"
   ip_address="127.0.0.1"
else
   info "NOTE: You can type '${NC}?${blue}' in response to any question for a hint"
   interactive
fi

dbg "Applying Kazoo configuration..."

set_value amqp_string $amqp_string
set_value cookie $cookie
set_value ip_address $ip_address

clean_exit $lockfile




