#!/usr/bin/env bash

set -e
set -o nounset

#logfile
#lock_file
lockfile="/var/lock/subsys/setup_kamailio.lockfile"

#Files to edit
kamailio_local_cfg="/etc/kazoo/kamailio/local.cfg"
kamailio_dispatcher="/etc/kazoo/kamailio/dbtext/dispatcher"

. /opt/kazoo_install/setup_common
trap error_exit SIGHUP SIGTERM ERR EXIT
trap int_exit SIGINT SIGQUIT

declare -a dispatch_list

#KAMAILIO IP ADDRESS
ip_address=""
ip_address_dbg="setting $kamailio_local_cfg - !MY_IP_ADDRESS!TOKEN"
ip_address_cmd="sed -i 's/!MY_IP_ADDRESS!.*!/!MY_IP_ADDRESS!TOKEN!/g' $kamailio_local_cfg"
ip_address_question="Please enter the IP address that kamailio should use for sip (ip_address): "
ip_address_re="$ip_address_regex"
ip_address_hint="IP ADDRESS!"
ip_address_ref="ip_address"

#KAMAILIO HOSTNAME
system_hostname=""
system_hostname_dbg="setting $kamailio_local_cfg - !MY_HOSTNAME!TOKEN"
system_hostname_cmd="sed -i 's/!MY_HOSTNAME!.*!/!MY_HOSTNAME!TOKEN!/g' $kamailio_local_cfg"

#rabbitMQ AMQP server
amqp_address=""
amqp_address_dbg="setting $kamailio_local_cfg - !MY_AMQP_URL!TOKEN"
amqp_address_cmd="sed -i 's|!MY_AMQP_URL!.*!|!MY_AMQP_URL!amqp://guest:guest@TOKEN:5672|g' $kamailio_local_cfg"
amqp_address_question="Please enter the IP address that kamailio should use for amqp (rabbitmq server ip address): "
amqp_address_re=".*"
amqp_address_hint="This is the ip address of your rabbitmq-server"
amqp_address_ref="amqp_address"




interactive(){
    ask amqp_address
    ask ip_address
}

info " : Configuring Kamailio : "
check_root
check_lock
get_system_hostname

check_ip || ask_ip_selection

if [[ ${1:-} =~ -a ]];then
    all_in_one=1
fi

if [  ${all_in_one:-} ];then
   #if allinone we default everything!
   ip_address=$system_ip_address
   hostname=$system_hostname
   ports+=("11000")
   setids+=("1")
else
   info "NOTE: You can type '${NC}?${blue}' in response to any question for a hint"
   interactive
fi

dbg "Applying Kamailio configuration..."

if [[ ${system_ip_address:-} ]];then  
    set_value ip_address $system_ip_address
else
    set_value ip_address $ip_address
fi 


set_value system_hostname $system_hostname


clean_exit 
